version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    container_name: proyecto_isw_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env