services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: proyecto
    container_name: proyecto-db
    volumes:
      - ./postgres:/var/lib/postgresql/data